=== nedbat/coveragepy/lab/coverage-03.dtd
<!-- Portions (C) International Organization for Standardization 1986:
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->

<!ELEMENT coverage (sources?,packages)>
<!ATTLIST coverage line-rate   CDATA #REQUIRED>
<!ATTLIST coverage branch-rate CDATA #REQUIRED>
<!ATTLIST coverage version     CDATA #REQUIRED>
<!ATTLIST coverage timestamp   CDATA #REQUIRED>

<!ELEMENT sources (source*)>

<!ELEMENT source (#PCDATA)>

<!ELEMENT packages (package*)>

<!ELEMENT package (classes)>
<!ATTLIST package name        CDATA #REQUIRED>
<!ATTLIST package line-rate   CDATA #REQUIRED>
<!ATTLIST package branch-rate CDATA #REQUIRED>
<!ATTLIST package complexity  CDATA #REQUIRED>

<!ELEMENT classes (class*)>

<!ELEMENT class (methods,lines)>
<!ATTLIST class name        CDATA #REQUIRED>
<!ATTLIST class filename    CDATA #REQUIRED>
<!ATTLIST class line-rate   CDATA #REQUIRED>
<!ATTLIST class branch-rate CDATA #REQUIRED>
<!ATTLIST class complexity  CDATA #REQUIRED>

<!ELEMENT methods (method*)>

<!ELEMENT method (lines)>
<!ATTLIST method name        CDATA #REQUIRED>
<!ATTLIST method signature   CDATA #REQUIRED>
<!ATTLIST method line-rate   CDATA #REQUIRED>
<!ATTLIST method branch-rate CDATA #REQUIRED>

<!ELEMENT lines (line*)>

<!ELEMENT line (conditions*)>
<!ATTLIST line number CDATA #REQUIRED>
<!ATTLIST line hits   CDATA #REQUIRED>
<!ATTLIST line branch CDATA "false">
<!ATTLIST line condition-coverage CDATA "100%">

<!ELEMENT conditions (condition*)>

<!ELEMENT condition EMPTY>
<!ATTLIST condition number CDATA #REQUIRED>
<!ATTLIST condition type CDATA #REQUIRED>
<!ATTLIST condition coverage CDATA #REQUIRED>

=== nedbat/coveragepy/tests/farm/html/gold_y_xml_branch/coverage.xml
<?xml version="1.0" ?>
<!DOCTYPE coverage
  SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-03.dtd'>
<coverage branch-rate="0.5" line-rate="0.8" timestamp="1259288252325" version="3.2b4">
	<!-- Generated by coverage.py: http://nedbatchelder.com/code/coverage/VER -->
	<sources>
		<source></source>
	</sources>
	<packages>
		<package branch-rate="0.5" complexity="0" line-rate="0.8" name=".">
			<classes>
				<class branch-rate="0.5" complexity="0" filename="y.py" line-rate="0.8" name="y.py">
					<methods/>
					<lines>
						<line hits="1" number="3"/>
						<line branch="true" condition-coverage="50% (1/2)" hits="1" number="4"/>
						<line hits="1" number="5"/>
						<line hits="0" number="7"/>
						<line hits="1" number="9"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>

=== nedbat/coveragepy/test/farm/html/gold_x_xml/coverage.xml
<?xml version="1.0" ?>
<!DOCTYPE coverage
  SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-03.dtd'>
<coverage branch-rate="0.0" line-rate="0.666666666667" timestamp="1253972570431" version="3.1b1">
	<!-- Generated by coverage.py: http://nedbatchelder.com/code/coverage -->
	<packages>
		<package branch-rate="0.0" complexity="0.0" line-rate="0.666666666667" name=".">
			<classes>
				<class branch-rate="0.0" complexity="0.0" filename="a.py" line-rate="0.666666666667" name="a">
					<methods/>
					<lines>
						<line hits="1" number="3"/>
						<line hits="1" number="5"/>
						<line hits="0" number="7"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
